### ISSUE TITLE
anime news future

### ISSUE THREAD

**Issue by samerbes** [PrajjwalDatir/Kaoi#107]
A future that make the bot sends anime news in the chat

And you can make it word in dm too

**Comment by PrajjwalDatir** [comment]
@bilal-08

**Comment by bilal-08** [comment]
> A future that make the bot sends anime news in the chat
> 
> And you can make it word in dm too

Yes That would be a great Feature 
we can use Myanimelist api or other if That's good
logic....we can use Cron job to occur every Certain amount of time 24 hr or 12hr 
and use Grp jids as first argument and Loop it one by one ,for that we can add them in array in database 
and another Feature i found - Anime Tracking

**Comment by PrajjwalDatir** [comment]
Let me know if anyone's interested in implementing it.
