### ISSUE TITLE
Custom `add` event message.

### ISSUE THREAD

**Issue by samerbes** [PrajjwalDatir/Kaoi#108]
Soo when someone joins the chat
You can enable a future when someone joins it sends the description

But sometimes it's useless

So my command request is to add a command that you can make kaoi send the message you wrote in command

example:
/{command name}  **welcome to chat**

So when someone join kaoi sends **welcome to chat**

**Comment by samerbes** [comment]
And I know you can change that by forking
But it's kinda annoying that you have to fork on every update

**Comment by PrajjwalDatir** [comment]
You mean, 
instead of the `description` as default, you want a custom message?

**Comment by samerbes** [comment]
> You mean, 
> instead of the `description` as default, you want a custom message?

Exactly

**Comment by bilal-08** [comment]
What would you do if you want to mention joined user in custom description , i mean it's not Easy :/

**Comment by PrajjwalDatir** [comment]
> What would you do if you want to mention joined user in custom description , i mean it's not Easy :/

It can be done. It can get the message from the user, and store it in the group db. And retrieve it instead of the following code.
```typescript
            ? `- ${group.subject || '___'} -\n\n💠 *Group Description:*\n${
                  group.desc
              }\n\nHope you follow the rules and have fun!\n${event.participants
```
https://github.com/PrajjwalDatir/Kaoi/blob/main/src/Handlers/EventHandler.ts#L20-L22

**Comment by bilal-08** [comment]
> > What would you do if you want to mention joined user in custom description , i mean it's not Easy :/
> 
> It can be done. It can get the message from the user, and store it in the group db. And retrieve it instead of the following code.
> 
> ```ts
>             ? `- ${group.subject || '___'} -\n\n💠 *Group Description:*\n${
>                   group.desc
>               }\n\nHope you follow the rules and have fun!\n${event.participants
> ```
> 
> https://github.com/PrajjwalDatir/Kaoi/blob/main/src/Handlers/EventHandler.ts#L20-L22

Ohh wow didnt thought abt that :O

**Comment by PrajjwalDatir** [comment]
> > > What would you do if you want to mention joined user in custom description , i mean it's not Easy :/
> > 
> > 
> > It can be done. It can get the message from the user, and store it in the group db. And retrieve it instead of the following code.
> > ```ts
> >             ? `- ${group.subject || '___'} -\n\n💠 *Group Description:*\n${
> >                   group.desc
> >               }\n\nHope you follow the rules and have fun!\n${event.participants
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://github.com/PrajjwalDatir/Kaoi/blob/main/src/Handlers/EventHandler.ts#L20-L22
> 
> Ohh wow didnt thought abt that :O

You can give it a try, if you want to ofc
