### ISSUE TITLE
Enchantment idea in comment

### ISSUE THREAD

**Issue by samerbes** [PrajjwalDatir/Kaoi#109]
So kaoi is actually getting every message that shows up and put it in heroku
It's kinda useless for users
And xp in kaoi is also kinda useless

So I recommend that you make xp earined by message's in chat
Even if it wasn't a command

So we can fork kaoi and make a price's for every 5 levels or something like that

**Comment by PrajjwalDatir** [comment]
To increase xp for each message. we'll need to `access` the user jid (user unique id) and update the `database`.
The DB updates per message is simply too costly ( in terms of processing time ). Hence not doable / worth it.

Also, a Good thing is, I'm thinking about adding levels based on the XP.
and XP is useful in groups which are made for command usage.
