### ISSUE TITLE
Adding more Features 

### ISSUE THREAD

**Issue by Hiroto77** [PrajjwalDatir/Kaoi#119]
`Request for adding commands`

1. Add Broadcast Command
2. Needed ADD command
3. New cool APIs for neko and waifu

**Comment by Hiroto77** [comment]
@PrajjwalDatir

**Comment by PrajjwalDatir** [comment]
Make a separate issue for each command/enhancement.
and check whether this issue is reported earlier or not, here
https://github.com/PrajjwalDatir/Kaoi/issues
