### ISSUE TITLE
Cool look of Help list.

### ISSUE THREAD

**Issue by Hiroto77** [PrajjwalDatir/Kaoi#120]
Adding pic with some cool looking title.
Using ExternalAdReply.

**Comment by PrajjwalDatir** [comment]
Can you elaborate? What kind of title do you meant?

**Comment by bilal-08** [comment]
aside from title,  i think the image might slow down the bot functionality :|

**Comment by PrajjwalDatir** [comment]
YES @bilal-08 
+ It'll fill the gallery with the bot images.

Anyway, I'm thinking about giving the user access to small configurations like image in help : on/off
ChatBot : on/off , etc

**Comment by bilal-08** [comment]
> YES @bilal-08
> 
> * It'll fill the gallery with the bot images.
> 
> Anyway, I'm thinking about giving the user access to small configurations like image in help : on/off ChatBot : on/off , etc

Yes i agree on First point 
+ that would be good To have configuration 
+ we can use Apis in images or Botto kaoi's Banner image :) [have to make one]
