### ISSUE TITLE
Adding Some features

### ISSUE THREAD

**Issue by Hiroto77** [PrajjwalDatir/Kaoi#126]
🟢 ```join <gc url>```
*Info:* Bot to join the group(command for Bot owner (Mods)only)

```broadcast/bc```
*info:* broadcast in groups Bot is in. (Only For Mods)

```grouplist```
*info:* get list of groups where Bot is running

```active```
*Info:* get list of members online in a group

 🟢 ```delete```
*info:* delete text or media sent by Bot

```truth or dare(t or d)```
*Info:* play truth or dare game*

```rules```
*info:* get rules of Bot

```translate <language> <text>```
*info:* translate text into given language

```toimg```
*info:* convert sticker into image

```togif```
*info:* convert sticker into gif

```calc```
*info:* get answer of a given mathematical expression

 🟢 ```enable/disable <command_name>```
*info:* (no description)

⚠️ ```add 914556****```
*info:* add the contact to the group chat(group admin only command)

```revoke```
*info:* Reset the group link

And lastly ```Bot should send a message immediately after joining a group so everyone will know there is one useful Bot in the group```

```link```
*info:* Fetch the group link if BotAdmin = True

**Comment by PrajjwalDatir** [comment]
`Join` Implemented
`delete`  Implemented
`enable/disable` Implemented

`add` has a chance of getting the bot banned.

@Hiroto77 Please edit your first comment and write :green_circle:  in front of Implemented commands.
:warning:  In front of features which might be dangerous like getting the number banned.

Also for `groupLink` refer to this https://github.com/PrajjwalDatir/Kaoi/issues/32
@Hiroto77 @alceil @Nisarga-Developer @ShinNouzen Can one of you pick up with this? :smile:

**Comment by PrajjwalDatir** [comment]
revoke
link
Done @Hiroto77
