### ISSUE TITLE
F**K everything 

### ISSUE THREAD

**Issue by bilal-08** [PrajjwalDatir/Kaoi#127]
.

**Comment by bilal-08** [comment]
Update : 
 
 shuffled the whole array
const shuffled = user.sort(()=> 0.5 - [add a value in decimal or use Math.random()])

 cut out / pick out some value first n shuffled value with Array.slice.()


const pick = shuffled.slice(0,n)

**Comment by PrajjwalDatir** [comment]
Wow!
This is good.
Can you tell us the use cases of `pick` feature?

**Comment by bilal-08** [comment]
> Wow! This is good. Can you tell us the use cases of `pick` feature?
 
=> pick My bestto Friendo!
=> pick my Gf :D
=> pick A 🏳️‍🌈 
=> pick 3 Group project A 
=>Pick 3 group Project B 

(You have a class project you have to Make in Group of 3 And that is how you can decide:)

**Comment by Nisarga-Developer** [comment]
Nice!! The command is insightful and interesting. 👏
