### ISSUE TITLE
Heroku App Sleeping

### ISSUE THREAD

**Issue by Raj6544** [PrajjwalDatir/Kaoi#144]
The bot often have Been disconnected from Google web after sometimes of connecting it. There is no issue with internet or wifi. It continues oftenly

**Comment by PrajjwalDatir** [comment]
Can you elaborate on what do you mean by `google web` ?
Do you mean app goes to sleep after 30min of inactivity?

**Comment by Raj6544** [comment]
@PrajjwalDatir Thank you. It worked
