### ISSUE TITLE
Enhancement request #8

### ISSUE THREAD

**Issue by AB1RZ9** [PrajjwalDatir/Kaoi#15]
I'll really like to ask you to add the broadcast command in the repo so that mods can atleast broadcast something important like giving a brief downtime or announcing something. Copy pasta is really hard when the bot number is on more than 20 gcs.
Another small request is to make the google command public and not only moderators, ig there's some modules that can help doing it. (I could've tried this on my own but my situation is just worse)

**Comment by PrajjwalDatir** [comment]
1. Yes I will look into Google Command. Currently way to do it without using the official API, is using a `Cheerio` NPM package which all basically do web scrapping which makes the bot heavier.
Right now I am little busy with my work hence I'm only looking for APIs.

2. Yes I do agree about adding the Broadcast command. But before adding the broadcast command. I want to add the Mute and Unmute command. So groups won't be spammed by Broadcasts.
Let's see... I will look into it soon

**Comment by PrajjwalDatir** [comment]
Broadcast #33 
Google Command #34
