### ISSUE TITLE
Image fetching issue 

### ISSUE THREAD

**Issue by Raj6544** [PrajjwalDatir/Kaoi#161]
![IMG_20211015_183321](https://user-images.githubusercontent.com/92223399/137491458-2e5cb1b6-94f2-4f7b-a721-f9618a014514.jpg)
failed to fetch images.

**Comment by Raj6544** [comment]
@PrajjwalDatir it's not only waifu. Failed to fetch all anime images.

**Comment by ShinNouzen** [comment]
Deploy [Chitoge](https://github.com/ShinNouzen/Chitoge).
