### ISSUE TITLE
[Request] To-Image

### ISSUE THREAD

**Issue by asdfghjkltgb** [PrajjwalDatir/Kaoi#17]
Plox see my requests : 
+ toimg
+ trigger cmd for Quoted image
+ sticker-tag
+Find Images from google and then Send out put as Stickers

**Comment by PrajjwalDatir** [comment]
> toimg : 

soon

> trigger for Quoted image : 

Will do on this weekend

> sticker-tag

Need to check for NSFW filter
Before Implementing this.
