### ISSUE TITLE
Anti-grouplink and no bad words feature

### ISSUE THREAD

**Issue by Liton124** [PrajjwalDatir/Kaoi#170]
Please add anti-grouplink and no bad words feature in groups.

ANTI-GROUP LINK
Condition: if any user in the group sends group links, the user will be warned for deleting the link/links. If the user doesn't delete the link/links in a specific time (it can be 1or 2 min), the user will be removed. 

NO BAD WORDS
condition: first time the user will be warned for saying the bad or abusive words, next time if the user again use bad or abusive words then he will be removed.

**Comment by PrajjwalDatir** [comment]
Ok, Will look into it
