### ISSUE TITLE
Qr code

### ISSUE THREAD

**Issue by RiasBack** [PrajjwalDatir/Kaoi#226]
{"message":"QR is not generated yet"} < how? Did i wrong something or?

**Comment by Oreki-san** [comment]
> {"message":"QR is not generated yet"} < how? Did i wrong something orchanging session id 

> {"message":"QR is not generated yet"} < how? Did i wrong something or?

Change session id and try

**Comment by RiasBack** [comment]
> > {"message":"QR is not generated yet"} < how? Did i wrong something orchanging session id
> 
> > {"message":"QR is not generated yet"} < how? Did i wrong something or?
> 
> Change session id and try

How to change the session id

**Comment by Oreki-san** [comment]
> > > {"message":"QR is not generated yet"} < how? Did i wrong something orchanging session id
> > 
> > 
> > > {"message":"QR is not generated yet"} < how? Did i wrong something or?
> > 
> > 
> > Change session id and try
> 
> How to change the session id

- go in heroku app
- settings
- reveal config vars
- change session
- open app

**Comment by Nisarga-Developer** [comment]
Reload page
