### ISSUE TITLE
Bot not working in new group chats

### ISSUE THREAD

**Issue by PabloChocobar69** [PrajjwalDatir/Kaoi#235]
The bot isn't working in new group chats except for the group chats created by the Business account. Need to update bot to new `3.5.3` v/ of [Baileys](https://github.com/adiwajshing/Baileys).

A look at [This](https://github.com/adiwajshing/Baileys/commit/b616cf5aca487ec80d068beedbe3e4d14f0eafca) and [This](https://github.com/adiwajshing/Baileys/pull/851) might help.

**Comment by viniciusgdr** [comment]
> The bot isn't working in new group chats except for the group chats created by the Business account. Need to update bot to new `3.5.2` v/ of [Baileys](https://github.com/adiwajshing/Baileys).
> 
> A look at [This](https://github.com/adiwajshing/Baileys/commit/b616cf5aca487ec80d068beedbe3e4d14f0eafca) and [This](https://github.com/adiwajshing/Baileys/pull/851) might help.

Update your baileys...
npm install github:adiwajshing/baileys

**Comment by ShinNouzen** [comment]
> > The bot isn't working in new group chats except for the group chats created by the Business account. Need to update bot to new `3.5.2` v/ of [Baileys](https://github.com/adiwajshing/Baileys).
> > A look at [This](https://github.com/adiwajshing/Baileys/commit/b616cf5aca487ec80d068beedbe3e4d14f0eafca) and [This](https://github.com/adiwajshing/Baileys/pull/851) might help.
> 
> Update your baileys... npm install github:adiwajshing/baileys

should be `yarn add`

**Comment by Nisarga-Developer** [comment]
run yarn add

**Comment by PabloChocobar69** [comment]
Issue resolved. Maintainers kindly merge the PR request.
