### ISSUE TITLE
Bot is not working

### ISSUE THREAD

**Issue by silent-zorro** [PrajjwalDatir/Kaoi#236]
heroku shows there is no such app when logging to session

**Comment by Liton124** [comment]
Exactly!! Same problem

**Comment by silent-zorro** [comment]
> Exactly!! Same problem

Any solution for this issue? I just took a look at the log. It automatically generates a few more QR and after that, it shows some error. before this issue, there was only one QRC.

**Comment by Liton124** [comment]
@silent-zorro Baileys problem ig

**Comment by silent-zorro** [comment]
> @silent-zorro Baileys problem ig

Will this problem be permanent or will be solved soon?
