### ISSUE TITLE
Bot ERROR

### ISSUE THREAD

**Issue by silent-zorro** [PrajjwalDatir/Kaoi#240]
The bot is **not working in groups**. No response from the bot. Can anyone explain this problem?

**Comment by PabloChocobar69** [comment]
Refer to #235

**Comment by silent-zorro** [comment]
> Refer to #235

 Can you please tell me how to update Baileys?

**Comment by PabloChocobar69** [comment]
> > Refer to #235
> 
> Can you please tell me how to update Baileys?

Make a PR to fix the issue wait till maintainers merge the PR request.
