### ISSUE TITLE
Private chat Issue

### ISSUE THREAD

**Issue by silent-zorro** [PrajjwalDatir/Kaoi#250]
while chatting in private, the chatbot is disturbing to the chat. How to deactivate it? I don't want to remove the brain shop link also.

**Comment by ShineiIchijo** [comment]
Check [MessageHandler](https://github.com/PrajjwalDatir/Kaoi/blob/main/src/Handlers/MessageHandler.ts)

**Comment by silent-zorro** [comment]
> Check [MessageHandler](https://github.com/PrajjwalDatir/Kaoi/blob/main/src/Handlers/MessageHandler.ts)

Can It change to reply when  I am away from the chat? While I am chatting, the bot also sends messages to chat...

**Comment by ShineiIchijo** [comment]
> > Check [MessageHandler](https://github.com/PrajjwalDatir/Kaoi/blob/main/src/Handlers/MessageHandler.ts)
> 
> Can It change to reply when I am away from the chat? While I am chatting, the bot also sends messages to chat...

Ahh.... Can you please elaborate?

**Comment by silent-zorro** [comment]
> 

When I am chatting In private chats, Bot is sending messages as well. So bot replies to every message and it interrupts ongoing chat. The bot responds to every message like me when I am also sending messages. Every time when this happens I have to remove the linked device to turn off it.

**Comment by ShineiIchijo** [comment]
> > 
> 
> When I am chatting In private chats, Bot is sending messages as well. So bot replies to every message and it interrupts ongoing chat. The bot responds to every message like me when I am also sending messages. Every time when this happens I have to remove the linked device to turn off it.

Please check the [MessageHandler](https://github.com/PrajjwalDatir/Kaoi/blob/main/src/Handlers/MessageHandler.ts) and you'll find the solution for it.

**Comment by silent-zorro** [comment]
> > > 
> > 
> > 
> > When I am chatting In private chats, Bot is sending messages as well. So bot replies to every message and it interrupts ongoing chat. The bot responds to every message like me when I am also sending messages. Every time when this happens I have to remove the linked device to turn off it.
> 
> Please check the [MessageHandler](https://github.com/PrajjwalDatir/Kaoi/blob/main/src/Handlers/MessageHandler.ts) and you'll find the solution for it.

Ok, Thank you.....
