### ISSUE TITLE
Bug in `Sticker`

### ISSUE THREAD

**Issue by PrajjwalDatir** [PrajjwalDatir/Kaoi#26]
`Sticker` for too long Video/Gifs ends up in an infinite loop of ffmpeg.
which a) hangs the localhost system
b) makes the pm2 restart the process. Resulting in Bot down for few seconds everytime someone uses the Sticker for Too long video/gifs

Logs : 
> 0|void     |     at ChildProcess.<anonymous> (/home/monarch/Kaoi/node_modules/fluent-ffmpeg/lib/processor.js:180:22)
0|void     |     at ChildProcess.emit (events.js:400:28)
0|void     |     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
0|void     | Error: ffmpeg was killed with signal SIGKILL

![image](https://user-images.githubusercontent.com/46681482/130472906-331a5998-796b-417d-aca0-44f6ca15d2a1.png)

**Comment by PrajjwalDatir** [comment]
@alensaito1 can you check whether,

https://github.com/AlenSaito1/wa-sticker-formatter/issues/12

This is the cause of the Bug?

**Comment by AlenSaito1** [comment]
Can you maybe try with the github version? `yarn add github:wa-sticker-formatter`

**Comment by PrajjwalDatir** [comment]
Fixed with 4442a04ada55cbbbda466c205f5095fe9bae3073
