### ISSUE TITLE
Command Request `Broadcast`

### ISSUE THREAD

**Issue by PrajjwalDatir** [PrajjwalDatir/Kaoi#33]
1. Create a new field in Group Model as `canBroadcast`
2. check if the group has `canBroadcast` = `true`
3. broadcast the message in the group, if it's true.

**Comment by alceil** [comment]
Can i work on this issue?

**Comment by PrajjwalDatir** [comment]
Yes @alceil

**Comment by alceil** [comment]
Can i get any reference for this issue? @PrajjwalDatir

**Comment by PrajjwalDatir** [comment]
@alceil 
1. Create a new field in Group Model as canBroadcast
Everytime the command is triggered
2. Loop through all the groups in the db
3. check if the group has canBroadcast = true
4. broadcast the message in the group, if it's true.

You can use https://adiwajshing.github.io/Baileys/classes/waconnection.html#sendmessage
Here, define the parameter as `group` and in `id` use the group jid, which is stored in the group db

**Comment by alceil** [comment]
Got it
