### ISSUE TITLE
Command Request `Google`

### ISSUE THREAD

**Issue by PrajjwalDatir** [PrajjwalDatir/Kaoi#34]
Google search in whatsapp!
But not using official API which only provides 100 searches a day!

**Comment by PrajjwalDatir** [comment]
Help me find an API which provides Google Search Results with no restrictions.

**Comment by Nisarga-Developer** [comment]
https://api.abirhasan.wtf/documentation

There is a google search API there, free.
And please make the command as everyone (even if they are not admin) can use it.

**Comment by PrajjwalDatir** [comment]
54ef7631cdb94d93bd4dda6f507940c4fa80ff05
