### ISSUE TITLE
`chatbot` working in Personal Messages

### ISSUE THREAD

**Issue by PrajjwalDatir** [PrajjwalDatir/Kaoi#49]
Chatbot which should be capable of having Human-like conversation in Personal Messaging

**Comment by AlenSaito1** [comment]
https://brainshop.ai/

**Comment by Nisarga-Developer** [comment]
https://www.npmjs.com/package/cleverbot-api-free

**Comment by PrajjwalDatir** [comment]
Implemented in b01e679488102c636f02e570cff4fa5cf6432fcc
