### ISSUE TITLE
waifu is done. where's the `husbu`

### ISSUE THREAD

**Issue by PrajjwalDatir** [PrajjwalDatir/Kaoi#52]
steal someone's API and supply husbus

**Comment by Nisarga-Developer** [comment]
Use https://nekos.life buddy

**Comment by selk21** [comment]
I looked into this issue, but I couldn't seem to find any endpoints that relate to husbando images for the nekos.life API.

**Comment by PrajjwalDatir** [comment]
@selk21  
https://mywaifulist.docs.stoplight.io/api-reference/husbando/get-husbando-images
Have a look at this, it might be useful

**Comment by Nisarga-Developer** [comment]
I think it's already done #86
