### ISSUE TITLE
Need `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by PrajjwalDatir** [PrajjwalDatir/Kaoi#61]
this is an example template https://gist.github.com/PurpleBooth/b24679402957c63ec426

We need CONTRIBUTING.md file to explain the process and rules of contributing to the community.
It's more like a formal document, not related to coding. So anyone with Good English & little knowledge about Open Source can do it.

**Comment by Dhi13man** [comment]
Please assign. On it already. :)

**Comment by PrajjwalDatir** [comment]
Done
