### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by PabloChocobar69** [PrajjwalDatir/Kaoi#7]
Your bot is working flawlessly with 0 downtime. Thanks to the easy setup link and video you provided! I would like to request some enhancement features that will help with the productivity of the bot.
Could you please kindly add

/grouplink - To fetch group link where the bot is added.

/add (+91number)~ To add any number to the group by typing this command only by admins.

/warn - To give warning to a user who spams or sends suspicious links. A member can get a total of 3 warnings and gets automatically kicked when he/she is warned for the 3rd time. (executed by admins by typing the /warn command also mentioning the reason for warn)

/toggle ~ To toggle on/off disappearing messages.

/setdec ~ To set group description.

/setname - To change group's name.

/Roast - a short evil roast 
 Fetch from the list of really evil nasty roast lines saved in the library of the bot

/Images - does a image search

/Memes - lists a meme temaplate or make meme
 ex: memes list
 ex: memes make two buttons

/Joke - cracks a joke as specified
Ex: /joke random
      /joke programming

/Advice - gives a random life advice from adviceslip.com

/tts ~ To convert text to speech (/ttsm for male voice &/ttsf for female voice)

/admins - To tag all admins by group members/admins.

Lastly toggling command for the "welcome" and the "goodbye" message on and off separately. In a group people may join & leaves often, so toggling on only the welcome text and disabling the goodbye message makes more sense. Later if if the admin wishes he may turn the goodbye message on by using a command say "/Act goodbye".

Appreciate the great minds behind these amazing bots.

**Comment by PrajjwalDatir** [comment]
> /grouplink - To fetch group link where the bot is added.

I'll try : Priority : Medium

> /add (+91number)~ To add any number to the group by typing this command only by admins.

I'll try : Priority : High

> /warn - To give warning to a user who spams or sends suspicious links. A member can get a total of 3 warnings and gets automatically kicked when he/she is warned for the 3rd time. (executed by admins by typing the /warn command also mentioning the reason for warn)

I'll try : Priority : Medium

> /toggle ~ To toggle on/off disappearing messages.

I'll try : Priority : Low

> /setdec ~ To set group description.

I'll try : Priority : Medium

> /setname - To change group's name.

I'll try : Priority : Medium

> /Roast - a short evil roast

Fetch from the list of really evil nasty roast lines saved in the library of the bot
Um, I don't think roasts should be there in **Kaoi**...

> /Images - does a image search

It's hard to check for the NSFW when doing the Image Search
I'll have to think on this.

> /Memes - lists a meme temaplate or make meme
ex: memes list
ex: memes make two buttons

Umm do you know any API for making memes? Else we would have to do image processing stuff which is little time consuming...

> /Joke - cracks a joke as specified
Ex: /joke random
/joke programming

Most of the APIs I saw makes cringe jokes.. If you know a place with good collection of Jokes then only I'm interested in this.

> /Advice - gives a random life advice from adviceslip.com

Ask your friends and elders for advice :)

> /tts ~ To convert text to speech (/ttsm for male voice &/ttsf for female voice)

I'll try : Priority : Low

> /admins - To tag all admins by group members/admins.

This already exists

**Comment by PabloChocobar69** [comment]
Also forgot but it would be good if you add the

 /open & /close - /open to allow all the participants to send text in a group chat or /close to only allow admins to send text in a group chat.

**Comment by PrajjwalDatir** [comment]
Also please make new issue for new issues.
Here on-wards
so We can track it properly
