### ISSUE TITLE
Set group command limits per hour command

### ISSUE THREAD

**Issue by samerbes** [PrajjwalDatir/Kaoi#96]

**Comment by PrajjwalDatir** [comment]
why would you want to do it?
And do you want to limit commands per group or per user?

**Comment by samerbes** [comment]
> why would you want to do it?
> And do you want to limit commands per group or per user?

So nobody spam commands for nothing 
And i prefer to make it per user
But if ita per group no problem

**Comment by PrajjwalDatir** [comment]
Okay I think per user would be better. I will try to implement it soon.
