### ISSUE TITLE
Gif Sticker issue 

### ISSUE THREAD

**Issue by iamherok** [PrajjwalDatir/Kaoi#97]
The gif sticker fracture is not working properly

**Comment by PrajjwalDatir** [comment]
Can you please provide the screenshot of the sticker and original gif?

**Comment by Whatup364** [comment]
I also have same issue

**Comment by Whatup364** [comment]
https://www.mediafire.com/file/9253slvbo1jqxcb/Record_2021-09-27-19-26-55_9fcd5e8691ecf6998421ed853039a579.mp4/file

Here is a video link for proof

**Comment by Whatup364** [comment]
![Screenshot_2021-09-27-20-08-26-61_9fcd5e8691ecf6998421ed853039a579](https://user-images.githubusercontent.com/89797110/134930368-74b81df7-91ff-4331-a23e-783173373dbc.jpg)
Ss proof

**Comment by Whatup364** [comment]
@PrajjwalDatir

**Comment by PrajjwalDatir** [comment]
Ok. Thank you for reporting the issue. We'll start working on it.

@aceu1 @ShinNouzen @alensaito1 @Hiroto77 @Nakshatra4762  @SimpFreakin
Any ideas?

**Comment by AlenSaito1** [comment]
Can confirm, caused by [WSF](https://github.com/AlenSaito1/wa-sticker-formatter). Blocked by https://github.com/lovell/sharp/pull/2789

**Comment by PrajjwalDatir** [comment]
Okay. we will wait till it's merged.

**Comment by Whatup364** [comment]
![Screenshot_2021-10-01-08-55-10-26_9fcd5e8691ecf6998421ed853039a579](https://user-images.githubusercontent.com/89797110/135560697-caac8f9b-59ea-450c-bf77-1dd6d1261cfe.jpg)

Wow new problem with gif sticker @PrajjwalDatir

**Comment by PrajjwalDatir** [comment]
@Whatup364 
So basically sticker is blank?
Can you tell us, how to reproduce this error?
Does it occur for lengthy GIFs, or for all GIFs?

**Comment by Whatup364** [comment]
Old error is back 😭

**Comment by Whatup364** [comment]
That error is gone

**Comment by Whatup364** [comment]
I just check what you said it is lengthy gif problem

**Comment by Whatup364** [comment]
Sorry for inconvenience

**Comment by Whatup364** [comment]
I am really sorry

**Comment by PrajjwalDatir** [comment]
> I just check what you said it is lengthy gif problem

Ok no problem! Thank you
